import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class LigaService {
  // Data lengkap tim Liga 1 untuk isi konten aplikasi
  private daftarTim = [
    {
      id: 'persib',
      nama: 'Persib Bandung',
      kota: 'Bandung',
      logo: 'https://upload.wikimedia.org/wikipedia/id/thumb/0/0d/Logo_Persib_Bandung.png/500px-Logo_Persib_Bandung.png',
      tahunBerdiri: 1933,
      sejarah:
        'Persib didirikan pada 14 Maret 1933. Merupakan penggabungan dari tiga klub bentukan pribumi yaitu BIVB dan NVB.',
      spesifikasi: {
        stadion: 'Gelora Bandung Lautan Api',
        kapasitas: '38,000',
        julukan: 'Maung Bandung',
        pelatih: 'Bojan Hodak',
      },
      prestasi: [
        { tahun: '2023/24', ket: 'Juara Liga 1 (Championship Series).' },
        { tahun: '2024/25', ket: 'Berkompetisi di AFC Champions League Two.' },
      ],
      lineup: [
        'Kevin Mendoza (Kiper / Goalkeeper)',
        'Teja Paku Alam (Kiper / Goalkeeper)',
        'Nick Kuipers (Bek Tengah / Center Back)',
        'Victor Igbonefo (Bek Tengah / Center Back)',
        'Achmad Jufriyanto (Bek Tengah / Center Back)',
        'Gustavo Franca (Bek Tengah / Center Back)',
        'Henhen Herdiana (Bek Kanan / Right Back)',
        'Edo Febriansah (Bek Kiri / Left Back)',
        'Rezaldi Hehanussa (Bek Kiri / Left Back)',
        'Daisuke Sato (Bek Kiri / Left Back)',
        'Marc Klok (Gelandang Tengah / Central Midfielder)',
        'Dedi Kusnandar (Gelandang Bertahan / Defensive Midfielder)',
        'Rachmat Irianto (Gelandang Bertahan / Defensive Midfielder)',
        'Beckham Putra (Gelandang Serang / Attacking Midfielder)',
        'Tyronne del Pino (Gelandang Serang / Attacking Midfielder)',
        'Mohammed Rashid (Gelandang Tengah / Central Midfielder)',
        'David da Silva (Penyerang Tengah / Center Forward)',
        'Ciro Alves (Penyerang Sayap / Winger)',
        'Febri Hariyadi (Penyerang Sayap / Winger)',
        'Frets Butuan (Penyerang Sayap / Winger)',
        'Wander Luiz (Penyerang Tengah / Center Forward)',
        'Dimas Drajad (Penyerang Tengah / Center Forward)',
      ],
    },
    {
      id: 'persija',
      nama: 'Persija Jakarta',
      kota: 'Jakarta',
      logo: 'https://upload.wikimedia.org/wikipedia/id/9/94/Persija_Jakarta_logo.png',
      tahunBerdiri: 1928,
      sejarah:
        'Lahir dengan nama VIJ pada 28 November 1928. Persija adalah salah satu pendiri PSSI.',
      spesifikasi: {
        stadion: 'Jakarta International Stadium',
        kapasitas: '82,000',
        julukan: 'Macan Kemayoran',
        pelatih: 'Carlos Pena',
      },
      prestasi: [
        { tahun: '2021', ket: 'Juara Piala Menpora.' },
        { tahun: '2022/23', ket: 'Runner-up Liga 1.' },
      ],
      lineup: [
        'Andritany Ardhiyasa (Kiper / Goalkeeper)',
        'Ondrej Kudela (Bek Tengah / Center Back)',
        'Rizky Ridho (Bek Tengah / Center Back)',
        'Otavio Dutra (Bek Tengah / Center Back)',
        'Maman Abdurahman (Bek Tengah / Center Back)',
        'Muhammad Ferarri (Bek Tengah / Center Back)',
        'Marco Motta (Bek Kanan / Right Back)',
        'Rio Fahmi (Bek Kanan / Right Back)',
        'Firza Andika (Bek Kiri / Left Back)',
        'Rezaldi Hehanussa (Bek Kiri / Left Back)',
        'Maciej Gajos (Gelandang Tengah / Central Midfielder)',
        'Ramon Bueno (Gelandang Bertahan / Defensive Midfielder)',
        'Hanno Behrens (Gelandang Serang / Attacking Midfielder)',
        'Syahrian Abimanyu (Gelandang Tengah / Central Midfielder)',
        'Marc Klok (Gelandang Tengah / Central Midfielder)',
        'Rohit Chand (Gelandang Bertahan / Defensive Midfielder)',
        'Ryo Matsumura (Penyerang Sayap / Winger)',
        'Riko Simanjuntak (Penyerang Sayap / Winger)',
        'Marko Simic (Penyerang Tengah / Center Forward)',
        'Michael Krmencik (Penyerang Tengah / Center Forward)',
        'Gustavo Almeida (Penyerang Tengah / Center Forward)',
        'Osvaldo Haay (Penyerang Sayap / Winger)',
      ],
    },
    {
      id: 'persebaya',
      nama: 'Persebaya Surabaya',
      kota: 'Surabaya',
      logo: 'https://upload.wikimedia.org/wikipedia/id/thumb/a/a1/Persebaya_logo.svg/250px-Persebaya_logo.svg.png',
      tahunBerdiri: 1927,
      sejarah:
        'Didirikan sebagai SIVB pada 18 Juni 1927. Dikenal dengan semangat "Wani" dan pendukung fanatik Bonek.',
      spesifikasi: {
        stadion: 'Gelora Bung Tomo',
        kapasitas: '45,000',
        julukan: 'Bajol Ijo',
        pelatih: 'Paul Munster',
      },
      prestasi: [
        { tahun: '2021/22', ket: 'Peringkat 5 Liga 1.' },
        {
          tahun: '2024/25',
          ket: 'Membangun skuad bertabur bintang untuk juara.',
        },
      ],
      lineup: [
        'Ernando Ari (Kiper / Goalkeeper)',
        'Rivky Mokodompit (Kiper / Goalkeeper)',
        'Slavko Damjanovic (Bek Tengah / Center Back)',
        'Dusan Stevanovic (Bek Tengah / Center Back)',
        'Leo Lelis (Bek Tengah / Center Back)',
        'Alie Sesay (Bek Tengah / Center Back)',
        'Rizky Ridho (Bek Tengah / Center Back)',
        'Koko Ari Araya (Bek Kanan / Right Back)',
        'Arisky Wahyu (Bek Kanan / Right Back)',
        'Reva Adi Utama (Bek Kiri / Left Back)',
        'Mikael Tata (Bek Kiri / Left Back)',
        'Mohammed Rashid (Gelandang Bertahan / Defensive Midfielder)',
        'Alwi Slamat (Gelandang Tengah / Central Midfielder)',
        'Gilson Costa (Gelandang Bertahan / Defensive Midfielder)',
        'Francisco Rivera (Gelandang Serang / Attacking Midfielder)',
        'Ze Valente (Gelandang Serang / Attacking Midfielder)',
        'Marselino Ferdinan (Gelandang Serang / Attacking Midfielder)',
        'Bruno Moreira (Penyerang Sayap / Winger)',
        'Taisei Marukawa (Penyerang Sayap / Winger)',
        'Malik Risaldi (Penyerang Sayap / Winger)',
        'Flavio Silva (Penyerang Tengah / Center Forward)',
        'Samsul Arif (Penyerang Tengah / Center Forward)',
        'Jose Wilkson (Penyerang Tengah / Center Forward)',
        'David da Silva (Penyerang Tengah / Center Forward)',
      ],
    },
    {
      id: 'arema',
      nama: 'Arema FC',
      kota: 'Malang',
      logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c2/Arema_FC_2017_logo.svg/1280px-Arema_FC_2017_logo.svg.png',
      tahunBerdiri: 1987,
      sejarah:
        'Lahir pada 11 Agustus 1987. Menjadi simbol kebanggaan warga Malang Raya (Aremania).',
      spesifikasi: {
        stadion: 'Stadion Kanjuruhan (Renovasi)',
        kapasitas: '30,000',
        julukan: 'Singo Edan',
        pelatih: 'Joel Cornelli',
      },
      prestasi: [
        { tahun: '2022', ket: 'Juara Piala Presiden.' },
        { tahun: '2024', ket: 'Juara Piala Presiden (Gelar ke-4).' },
      ],
      lineup: [
        'Lucas Frigeri (Kiper / Goalkeeper)',
        'Adilson Maringa (Kiper / Goalkeeper)',
        'Thales Lira (Bek Tengah / Center Back)',
        'Sergio Silva (Bek Tengah / Center Back)',
        'Bagis Adi Nugroho (Bek Tengah / Center Back)',
        'Choi Bo-kyeong (Bek Tengah / Center Back)',
        'Johan Alfarizi (Bek Kiri / Left Back)',
        'Achmad Figo (Bek Kanan / Right Back)',
        'Rizky Dwi Febrianto (Bek Kanan / Right Back)',
        'Julian Guevara (Gelandang Bertahan / Defensive Midfielder)',
        'Jayus Hariono (Gelandang Bertahan / Defensive Midfielder)',
        'Renshi Yamaguchi (Gelandang Tengah / Central Midfielder)',
        'Arkhan Fikri (Gelandang Tengah / Central Midfielder)',
        'Evan Dimas (Gelandang Serang / Attacking Midfielder)',
        'Wiliam Marcilio (Gelandang Serang / Attacking Midfielder)',
        'Gian Zola (Gelandang Serang / Attacking Midfielder)',
        'Charles Lokolingoy (Penyerang Sayap / Winger)',
        'Dendi Santoso (Penyerang Sayap / Winger)',
        'Dalberto (Penyerang Tengah / Center Forward)',
        'Carlos Fortes (Penyerang Tengah / Center Forward)',
        'Abel Camara (Penyerang Tengah / Center Forward)',
        'Dedik Setiawan (Penyerang Tengah / Center Forward)',
        'Kushedya Hari Yudo (Penyerang Sayap / Winger)',
      ],
    },
    {
      id: 'bali-united',
      nama: 'Bali United',
      kota: 'Gianyar',
      logo: 'https://upload.wikimedia.org/wikipedia/id/thumb/5/5e/Bali_United_logo.svg/250px-Bali_United_logo.svg.png',
      tahunBerdiri: 2014,
      sejarah:
        'Hasil akuisisi Persisam Putra Samarinda, kini menjadi klub paling modern dan profesional di Indonesia.',
      spesifikasi: {
        stadion: 'Kapten I Wayan Dipta',
        kapasitas: '18,000',
        julukan: 'Serdadu Tridatu',
        pelatih: 'Stefano Cugurra',
      },
      prestasi: [
        { tahun: '2021/22', ket: 'Juara Liga 1 (Back-to-back).' },
        { tahun: '2023/24', ket: 'Peringkat 4 Liga 1.' },
      ],
      lineup: [
        'Adilson Maringa (Kiper / Goalkeeper)',
        'Wawan Hendrawan (Kiper / Goalkeeper)',
        'Nadeo Argawinata (Kiper / Goalkeeper)',
        'Elias Dolah (Bek Tengah / Center Back)',
        'Willian Pacheco (Bek Tengah / Center Back)',
        'Ricky Fajrin (Bek Kiri / Left Back)',
        'Made Andhika Wijaya (Bek Kanan / Right Back)',
        'Novri Setiawan (Bek Kanan / Right Back)',
        'Ardi Idrus (Bek Kiri / Left Back)',
        'Brwa Nouri (Gelandang Bertahan / Defensive Midfielder)',
        'Mitsuru Maruoka (Gelandang Tengah / Central Midfielder)',
        'Mohammed Rashid (Gelandang Tengah / Central Midfielder)',
        'Eber Bessa (Gelandang Serang / Attacking Midfielder)',
        'Fadil Sausu (Gelandang Tengah / Central Midfielder)',
        'Sidik Saimima (Gelandang Tengah / Central Midfielder)',
        'Kenzo Nambu (Gelandang Serang / Attacking Midfielder)',
        'Privat Mbarga (Penyerang Sayap / Winger)',
        'M. Rahmat (Penyerang Sayap / Winger)',
        'Yabes Roni (Penyerang Sayap / Winger)',
        'Stefano Lilipaly (Penyerang Sayap / Winger)',
        'Ilija Spasojevic (Penyerang Tengah / Center Forward)',
        'Everton Nascimento (Penyerang Tengah / Center Forward)',
        'Jefferson Assis (Penyerang Tengah / Center Forward)',
      ],
    },
    {
      id: 'borneo-fc',
      nama: 'Borneo FC Samarinda',
      kota: 'Samarinda',
      logo: 'https://upload.wikimedia.org/wikipedia/id/thumb/4/4d/Logo_Borneo_FC.svg/250px-Logo_Borneo_FC.svg.png',
      tahunBerdiri: 2014,
      sejarah:
        'Klub asal Kalimantan yang konsisten di papan atas dengan manajemen yang sangat sehat.',
      spesifikasi: {
        stadion: 'Stadion Batakan (Sementara)',
        kapasitas: '40,000',
        julukan: 'Pesut Etam',
        pelatih: 'Pieter Huistra',
      },
      prestasi: [
        { tahun: '2023/24', ket: 'Juara Reguler Series Liga 1.' },
        {
          tahun: '2024/25',
          ket: 'Berkompetisi di Shopee Cup (ASEAN Club Championship).',
        },
      ],
      lineup: [
        'Nadeo Argawinata (Kiper / Goalkeeper)',
        'Gianluca Pandeynuwu (Kiper / Goalkeeper)',
        'Angga Saputro (Kiper / Goalkeeper)',
        'Ronaldo Rodrigues (Bek Tengah / Center Back)',
        'Silverio Junio (Bek Tengah / Center Back)',
        'Leo Lelis (Bek Tengah / Center Back)',
        'Javlon Guseynov (Bek Tengah / Center Back)',
        'Diego Michiels (Bek Kanan / Right Back)',
        'Fajar Fathurrahman (Bek Kanan / Right Back)',
        'Leo Guntara (Bek Kiri / Left Back)',
        'Kei Hirose (Gelandang Bertahan / Defensive Midfielder)',
        'Christophe Nduwarugira (Gelandang Bertahan / Defensive Midfielder)',
        'Hendro Siswanto (Gelandang Tengah / Central Midfielder)',
        'Adam Alis (Gelandang Sayap / Winger)',
        'Jonathan Bustos (Gelandang Serang / Attacking Midfielder)',
        'Wiljan Pluim (Gelandang Serang / Attacking Midfielder)',
        'Berguinho (Gelandang Serang / Attacking Midfielder)',
        'Stefano Lilipaly (Penyerang Sayap / Winger)',
        'Terens Puhiri (Penyerang Sayap / Winger)',
        'M. Sihran (Penyerang Sayap / Winger)',
        'Leo Gaucho (Penyerang Tengah / Center Forward)',
        'Matheus Pato (Penyerang Tengah / Center Forward)',
        'Felipe Cadenazzi (Penyerang Tengah / Center Forward)',
        'Francisco Torres (Penyerang Tengah / Center Forward)',
      ],
    },
    {
      id: 'psm',
      nama: 'PSM Makassar',
      kota: 'Makassar',
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Logo_PSM_Makassar_and_2_star.png/500px-Logo_PSM_Makassar_and_2_star.png',
      tahunBerdiri: 1915,
      sejarah:
        'Klub tertua di Indonesia. Menjadi kebanggaan masyarakat Sulawesi Selatan (Juku Eja).',
      spesifikasi: {
        stadion: 'Gelora B.J. Habibie',
        kapasitas: '20,000',
        julukan: 'Pasukan Ramang',
        pelatih: 'Bernardo Tavares',
      },
      prestasi: [
        { tahun: '2022/23', ket: 'Juara Liga 1 Indonesia.' },
        { tahun: '2024/25', ket: 'Berkompetisi di Shopee Cup.' },
      ],
      lineup: [
        'Hilman Syah (Kiper / Goalkeeper)',
        'Reza Arya Pratama (Kiper / Goalkeeper)',
        'Miswar Saputra (Kiper / Goalkeeper)',
        'Yuran Fernandes (Bek Tengah / Center Back)',
        'Aloisio Neto (Bek Tengah / Center Back)',
        'Safrudin Tahar (Bek Tengah / Center Back)',
        'Erwin Gutawa (Bek Tengah / Center Back)',
        'Yance Sayuri (Bek Sayap / Wing Back)',
        'Yakob Sayuri (Bek Sayap / Wing Back)',
        'Victor Luiz (Bek Kiri / Left Back)',
        'Daffa Salman (Bek Tengah / Center Back)',
        'Akbar Tanjung (Gelandang Bertahan / Defensive Midfielder)',
        'Ananda Raehan (Gelandang Tengah / Central Midfielder)',
        'M. Arfan (Gelandang Tengah / Central Midfielder)',
        'Latyr Fall (Gelandang Tengah / Central Midfielder)',
        'Kenzo Nambu (Gelandang Serang / Attacking Midfielder)',
        'Wiljan Pluim (Gelandang Serang / Attacking Midfielder)',
        'Daisuke Sakai (Gelandang Serang / Attacking Midfielder)',
        'Victor Mansaray (Penyerang Tengah / Center Forward)',
        'Tito Okello (Penyerang Tengah / Center Forward)',
        'Everton Nascimento (Penyerang Tengah / Center Forward)',
        'Adilson Silva (Penyerang Tengah / Center Forward)',
        'Ramadhan Sananta (Penyerang Tengah / Center Forward)',
        'Rizky Eka Pratama (Penyerang Sayap / Winger)',
      ],
    },
    {
      id: 'pss-sleman',
      nama: 'PSS Sleman',
      kota: 'Sleman',
      logo: 'https://upload.wikimedia.org/wikipedia/id/thumb/c/c9/PSS_Sleman_logo.svg/250px-PSS_Sleman_logo.svg.png',
      tahunBerdiri: 1976,
      sejarah:
        'Klub kebanggaan Sleman dengan suporter BCS yang dikenal memiliki kreativitas kelas dunia.',
      spesifikasi: {
        stadion: 'Maguwoharjo',
        kapasitas: '31,000',
        julukan: 'Super Elang Jawa',
        pelatih: 'Wagner Lopes',
      },
      prestasi: [
        { tahun: '2021', ket: 'Peringkat 3 Piala Menpora.' },
        { tahun: '2024/25', ket: 'Target 6 besar dengan skuad baru.' },
      ],
      lineup: [
        'Alan Bernardon (Kiper / Goalkeeper)',
        'Ega Rizky (Kiper / Goalkeeper)',
        'Anthony Pinthus (Kiper / Goalkeeper)',
        'Miswar Saputra (Kiper / Goalkeeper)',
        'Fachruddin Aryanto (Bek Tengah / Center Back)',
        'Thales Lira (Bek Tengah / Center Back)',
        'Aaron Evans (Bek Tengah / Center Back)',
        'Mario Maslac (Bek Tengah / Center Back)',
        'Phil Ofosu-Ayeh (Bek Kanan / Right Back)',
        'Bagus Nirwanto (Bek Kanan / Right Back)',
        'Abduh Lestaluhu (Bek Kiri / Left Back)',
        'Kevin Gomes (Bek Kiri / Left Back)',
        'Betinho (Gelandang Bertahan / Defensive Midfielder)',
        'Wahyudi Hamisi (Gelandang Bertahan / Defensive Midfielder)',
        'Kim Jeffrey Kurniawan (Gelandang Tengah / Central Midfielder)',
        'Jonathan Bustos (Gelandang Serang / Attacking Midfielder)',
        'Ze Valente (Gelandang Serang / Attacking Midfielder)',
        'Moon Chang-jin (Gelandang Serang / Attacking Midfielder)',
        'Irkham Mila (Penyerang Sayap / Winger)',
        'Ricky Cawor (Penyerang Sayap / Winger)',
        'Hokky Caraka (Penyerang Tengah / Center Forward)',
        'Gustavo Tocantins (Penyerang Tengah / Center Forward)',
        'Mychell Chagas (Penyerang Tengah / Center Forward)',
        'Wander Luiz (Penyerang Tengah / Center Forward)',
      ],
    },
    {
      id: 'barito-putera',
      nama: 'Barito Putera',
      kota: 'Banjarmasin',
      logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/4/46/Barito_Putera_logo-en.svg/500px-Barito_Putera_logo-en.svg.png',
      tahunBerdiri: 1988,
      sejarah:
        'Didirikan oleh H. Abdussamad Sulaiman HB, membawa misi memajukan sepak bola Kalimantan Selatan.',
      spesifikasi: {
        stadion: 'Sultan Agung (Sementara)',
        kapasitas: '15,000',
        julukan: 'Laskar Antasari',
        pelatih: 'Rahmad Darmawan',
      },
      prestasi: [
        { tahun: '2023/24', ket: 'Peringkat 10 Liga 1.' },
        { tahun: '2024/25', ket: 'Fokus pada regenerasi pemain muda.' },
      ],
      lineup: [
        'Satria Tama (Kiper / Goalkeeper)',
        'Adhitya Harlan (Kiper / Goalkeeper)',
        'Ega Rizky (Kiper / Goalkeeper)',
        'Lucao (Bek Tengah / Center Back)',
        'Renan Alves (Bek Tengah / Center Back)',
        'Cassio de Jesus (Bek Tengah / Center Back)',
        'Yuswanto Aditya (Bek Tengah / Center Back)',
        'Bagis Kahfi (Penyerang Sayap / Winger)',
        'Bagas Kaffa (Bek Kanan / Right Back)',
        'Frendi Saputra (Bek Kiri / Left Back)',
        'Hasim Kipuw (Bek Tengah / Center Back)',
        'Bayu Pradana (Gelandang Bertahan / Defensive Midfielder)',
        'Levy Madinda (Gelandang Serang / Attacking Midfielder)',
        'Makan Konate (Gelandang Serang / Attacking Midfielder)',
        'Mike Ott (Gelandang Tengah / Central Midfielder)',
        'Lucas Morelatto (Gelandang Tengah / Central Midfielder)',
        'Rizky Pora (Penyerang Sayap / Winger)',
        'Murilo Mendes (Penyerang Sayap / Winger)',
        'Ambrizal Umanailo (Penyerang Sayap / Winger)',
        'Youssef Ezzejjari (Penyerang Tengah / Center Forward)',
        'Gustavo Tocantins (Penyerang Tengah / Center Forward)',
        'Rafael Silva (Penyerang Tengah / Center Forward)',
        'Devid Silva (Penyerang Tengah / Center Forward)',
        'Exequiel Gallegos (Gelandang Serang / Attacking Midfielder)',
      ],
    },
    {
      id: 'dewa-united',
      nama: 'Dewa United FC',
      kota: 'Tangerang Selatan',
      logo: 'https://upload.wikimedia.org/wikipedia/id/5/53/Dewa_United_FC.png',
      tahunBerdiri: 2021,
      sejarah:
        'Akuisisi dari Martapura FC, menjelma menjadi "Los Galacticos" Indonesia karena finansial yang kuat.',
      spesifikasi: {
        stadion: 'Indomilk Arena',
        kapasitas: '15,000',
        julukan: 'Tangsel Warriors',
        pelatih: 'Jan Olde Riekerink',
      },
      prestasi: [
        { tahun: '2021', ket: 'Peringkat 3 Liga 2 (Promosi).' },
        { tahun: '2023/24', ket: 'Peringkat 5 Klasemen Reguler.' },
      ],
      lineup: [
        'Sonny Stevens (Kiper / Goalkeeper)',
        'Muhammad Natshir (Kiper / Goalkeeper)',
        'Risto Mitrevski (Bek Tengah / Center Back)',
        'Angelo Meneses (Bek Tengah / Center Back)',
        'Brian Fatari (Bek Tengah / Center Back)',
        'Achmad Faris (Bek Tengah / Center Back)',
        'Ady Setiawan (Bek Kanan / Right Back)',
        'Altalariq Ballah (Bek Kiri / Left Back)',
        'Rezaldi Hehanussa (Bek Kiri / Left Back)',
        'Theo Numberi (Gelandang Bertahan / Defensive Midfielder)',
        'Asep Berlian (Gelandang Bertahan / Defensive Midfielder)',
        'Alexis Messidoro (Gelandang Tengah / Central Midfielder)',
        'Jaja (Gelandang Tengah / Central Midfielder)',
        'Majed Osman (Gelandang Serang / Attacking Midfielder)',
        'Dimitris Kolovos (Gelandang Serang / Attacking Midfielder)',
        'Egy Maulana Vikri (Penyerang Sayap / Winger)',
        'Feby Eka Putra (Penyerang Sayap / Winger)',
        'Taisei Marukawa (Penyerang Sayap / Winger)',
        'Subhan Fajri (Penyerang Sayap / Winger)',
        'Alex Martins (Penyerang Tengah / Center Forward)',
        'Karim Rossi (Penyerang Tengah / Center Forward)',
        'Septian Bagaskara (Penyerang Tengah / Center Forward)',
      ],
    },
    {
      id: 'persik',
      nama: 'Persik Kediri',
      kota: 'Kediri',
      logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Logo_Persik_Kediri.jpg/250px-Logo_Persik_Kediri.png',
      tahunBerdiri: 1950,
      sejarah:
        'Pernah mengguncang Indonesia dengan juara beruntun dari kasta bawah hingga Liga Bank Mandiri.',
      spesifikasi: {
        stadion: 'Brawijaya',
        kapasitas: '20,000',
        julukan: 'Macan Putih',
        pelatih: 'Marcelo Rospide',
      },
      prestasi: [
        { tahun: '2023/24', ket: 'Peringkat 9 Liga 1.' },
        {
          tahun: '2024/25',
          ket: 'Target bersaing di zona Championship Series.',
        },
      ],
      lineup: [
        'Leonardo Navacchio (Kiper / Goalkeeper)',
        'Dikri Yusron (Kiper / Goalkeeper)',
        'Kurniawan Kartika Ajie (Kiper / Goalkeeper)',
        'Hamra Hehanussa (Bek Tengah / Center Back)',
        'Anderson Nascimento (Bek Tengah / Center Back)',
        'Arthur Felix (Bek Tengah / Center Back)',
        'Vava Mario Yagalo (Bek Tengah / Center Back)',
        'Kiko Carneiro (Bek Tengah / Center Back)',
        'Agil Munawar (Bek Kanan / Right Back)',
        'Yusuf Meilana (Bek Kiri / Left Back)',
        'Rohit Chand (Gelandang Bertahan / Defensive Midfielder)',
        'Bayu Otto (Gelandang Tengah / Central Midfielder)',
        'Ady Eko Jayanto (Gelandang Tengah / Central Midfielder)',
        'Ze Valente (Gelandang Serang / Attacking Midfielder)',
        'Renan Silva (Gelandang Serang / Attacking Midfielder)',
        'Majed Osman (Gelandang Serang / Attacking Midfielder)',
        'Ezra Walian (Penyerang Sayap / Winger)',
        'Hugo Samir (Penyerang Sayap / Winger)',
        'Fararis Roni (Penyerang Sayap / Winger)',
        'Yoseph Ezzejjari (Penyerang Tengah / Center Forward)',
        'Ramiro Fergonzi (Penyerang Tengah / Center Forward)',
        'Flavio Silva (Penyerang Tengah / Center Forward)',
        'Pedro Paulo (Penyerang Tengah / Center Forward)',
        'Jeam Kelly Sroyer (Penyerang Sayap / Winger)',
      ],
    },
    {
      id: 'persita',
      nama: 'Persita Tangerang',
      kota: 'Tangerang',
      logo: 'https://upload.wikimedia.org/wikipedia/id/thumb/9/95/Persita_logo_%282020%29.svg/500px-Persita_logo_%282020%29.svg.png',
      tahunBerdiri: 1953,
      sejarah:
        'Klub dengan identitas warna ungu yang kuat, menjadi representasi sepak bola Tangerang Raya.',
      spesifikasi: {
        stadion: 'Indomilk Arena',
        kapasitas: '15,000',
        julukan: 'Pendekar Cisadane',
        pelatih: 'Fabio Lefundes',
      },
      prestasi: [
        { tahun: '2019', ket: 'Runner-up Liga 2 (Promosi).' },
        { tahun: '2023/24', ket: 'Berhasil lolos dari zona degradasi.' },
      ],
      lineup: [
        'Igor Rodrigues (Kiper / Goalkeeper)',
        'Adhitya Harlan (Kiper / Goalkeeper)',
        'Annar Saputra (Kiper / Goalkeeper)',
        'Dhika Bayangkara (Kiper / Goalkeeper)',
        'Sandro Embalo (Bek Tengah / Center Back)',
        'Christian Rontini (Bek Tengah / Center Back)',
        'Javlon Guseynov (Bek Tengah / Center Back)',
        'Agustín Cattaneo (Bek Tengah / Center Back)',
        'Tamirlan Kozubaev (Bek Tengah / Center Back)',
        'Muhammad Toha (Bek Kanan / Right Back)',
        'Mario Jardel (Bek Kiri / Left Back)',
        'Edo Febriansah (Bek Kiri / Left Back)',
        'Bae Sin-yeong (Gelandang Bertahan / Defensive Midfielder)',
        'Fahreza Sudin (Gelandang Tengah / Central Midfielder)',
        'Ezequiel Vidal (Gelandang Serang / Attacking Midfielder)',
        'Mateo Bustos (Gelandang Serang / Attacking Midfielder)',
        'Harrison Cardoso (Gelandang Serang / Attacking Midfielder)',
        'Irsyad Maulana (Penyerang Sayap / Winger)',
        'Esal Sahrul (Penyerang Sayap / Winger)',
        'Marios Ogkmpoe (Penyerang Tengah / Center Forward)',
        'Yevhen Bokhashvili (Penyerang Tengah / Center Forward)',
        'Ramiro Fergonzi (Penyerang Tengah / Center Forward)',
        'Wildan Ramdhani (Penyerang Tengah / Center Forward)',
        'Alex Goncalves (Penyerang Tengah / Center Forward)',
      ],
    },
    {
      id: 'psbs',
      nama: 'PSBS Biak',
      kota: 'Biak Numfor',
      logo: 'https://upload.wikimedia.org/wikipedia/id/9/9b/Logo_PSBS_Biak_baru.png',
      tahunBerdiri: 1968,
      sejarah:
        'Klub asal Papua yang berhasil menembus kasta tertinggi dengan status juara Liga 2.',
      spesifikasi: {
        stadion: 'Stadion Kapten I Wayan Dipta (Sementara)',
        kapasitas: '18,000',
        julukan: 'Badai Pasifik',
        pelatih: 'Marcos Guillermo',
      },
      prestasi: [
        { tahun: '2023/24', ket: 'Juara Liga 2 Indonesia.' },
        { tahun: '2024/25', ket: 'Musim perdana di kasta tertinggi Liga 1.' },
      ],
      lineup: [
        'John Pigai (Kiper / Goalkeeper)',
        'Mario Londok (Kiper / Goalkeeper)',
        'Panggih Sambodo (Kiper / Goalkeeper)',
        'Julian Velazquez (Bek Tengah / Center Back)',
        'Donni Monim (Bek Tengah / Center Back)',
        'Otavio Dutra (Bek Tengah / Center Back)',
        'Fabiano Beltrame (Bek Tengah / Center Back)',
        'Yanto Basna (Bek Tengah / Center Back)',
        'Marckho Merauje (Bek Kanan / Right Back)',
        'Barnabas Sobor (Bek Kiri / Left Back)',
        'Jaimerson Xavier (Bek Tengah / Center Back)',
        'Jonata Machado (Gelandang Bertahan / Defensive Midfielder)',
        'Nelson Alom (Gelandang Bertahan / Defensive Midfielder)',
        'Williams Lugo (Gelandang Serang / Attacking Midfielder)',
        'Muhammad Tahir (Gelandang Tengah / Central Midfielder)',
        'Takuya Matsunaga (Gelandang Tengah / Central Midfielder)',
        'Madaninda (Gelandang Serang / Attacking Midfielder)',
        'Alexsandro Ferreira (Penyerang Tengah / Center Forward)',
        'Beto Goncalves (Penyerang Tengah / Center Forward)',
        'Abel Arganaraz (Penyerang Tengah / Center Forward)',
        'Jeam Kelly Sroyer (Penyerang Sayap / Winger)',
        'Todd Ferre (Penyerang Sayap / Winger)',
        'Gabriel Esparza (Penyerang Sayap / Winger)',
        'Melvis Urayani (Penyerang Sayap / Winger)',
      ],
    },
    {
      id: 'semen-padang',
      nama: 'Semen Padang FC',
      kota: 'Padang',
      logo: 'https://upload.wikimedia.org/wikipedia/min/1/1e/Semen_Padang_FC.png',
      tahunBerdiri: 1980,
      sejarah:
        'Klub legendaris asal Sumatera Barat yang kembali ke kasta tertinggi setelah beberapa musim di Liga 2.',
      spesifikasi: {
        stadion: 'H. Agus Salim',
        kapasitas: '20,000',
        julukan: 'Kabau Sirah',
        pelatih: 'Eduard Ivakdalam',
      },
      prestasi: [
        { tahun: '2023/24', ket: 'Runner-up Liga 2 Indonesia (Promosi).' },
        { tahun: '2024/25', ket: 'Target bertahan dan bersaing di Liga 1.' },
      ],
      lineup: [
        'Teguh Amiruddin (Kiper / Goalkeeper)',
        'Ikram Algiffari (Kiper / Goalkeeper)',
        'Fakhrurrazi Quba (Kiper / Goalkeeper)',
        'Achmad Ihwan (Kiper / Goalkeeper)',
        'Jan Vargas (Bek Tengah / Center Back)',
        'Kim Min-gyu (Bek Tengah / Center Back)',
        'Agus Nova (Bek Tengah / Center Back)',
        'Wiganda Pradika (Bek Kanan / Right Back)',
        'Dodi Alexvan Djin (Bek Kanan / Right Back)',
        'Frendi Saputra (Bek Kiri / Left Back)',
        'Miftah Anwar Sani (Bek Kiri / Left Back)',
        'Charlie Scott (Gelandang Bertahan / Defensive Midfielder)',
        'Rickii Ariansyah (Gelandang Bertahan / Defensive Midfielder)',
        'Rosad Setiawan (Gelandang Tengah / Central Midfielder)',
        'Bruno Dybal (Gelandang Serang / Attacking Midfielder)',
        'Ryohei Michibuchi (Penyerang Sayap / Winger)',
        'Firman Juliansyah (Penyerang Sayap / Winger)',
        'Vivi Asrizal (Penyerang Sayap / Winger)',
        'Alif Jaelani (Gelandang Serang / Attacking Midfielder)',
        'Kenneth Ngwoke (Penyerang Tengah / Center Forward)',
        'Ikechukwu Kimmy (Penyerang Tengah / Center Forward)',
        'Cornelius Stewart (Penyerang Tengah / Center Forward)',
        'Ahmad Ihwan (Penyerang Tengah / Center Forward)',
        'Muhammad Iqbal (Gelandang Tengah / Central Midfielder)',
      ],
    },
    {
      id: 'malut-united',
      nama: 'Malut United FC',
      kota: 'Sofifi',
      logo: 'https://upload.wikimedia.org/wikipedia/id/6/62/Malut_fc.png',
      tahunBerdiri: 2023,
      sejarah:
        'Hasil akuisisi Putra Delta Sidoarjo, klub ini merepresentasikan Maluku Utara di peta sepak bola nasional.',
      spesifikasi: {
        stadion: 'Stadion Gelora Kie Raha',
        kapasitas: '15,000',
        julukan: 'Laskar Kie Raha',
        pelatih: 'Imran Nahumarury',
      },
      prestasi: [
        { tahun: '2023/24', ket: 'Peringkat 3 Liga 2 (Promosi).' },
        {
          tahun: '2024/25',
          ket: 'Aktif mendatangkan pemain Timnas Indonesia.',
        },
      ],
      lineup: [
        'Muhammad Fahri (Kiper / Goalkeeper)',
        'Aldhila Ray Redondo (Kiper / Goalkeeper)',
        'Joko Ribowo (Kiper / Goalkeeper)',
        'Cassio Scheid (Bek Tengah / Center Back)',
        'Wahyu Prasetyo (Bek Tengah / Center Back)',
        'Safrudin Tahar (Bek Tengah / Center Back)',
        'Jeong Ho-min (Bek Tengah / Center Back)',
        'Rio Saputro (Bek Tengah / Center Back)',
        'Fredyan Wahyu (Bek Kanan / Right Back)',
        'Yakob Sayuri (Penyerang Sayap / Winger)',
        'Yance Sayuri (Bek Sayap / Wing Back)',
        'Bagis Nirwanto (Bek Kanan / Right Back)',
        'Manahati Lestusen (Gelandang Bertahan / Defensive Midfielder)',
        'Wbeymar Angulo (Gelandang Bertahan / Defensive Midfielder)',
        'Finky Pasamba (Gelandang Bertahan / Defensive Midfielder)',
        'Jorge Correa (Gelandang Serang / Attacking Midfielder)',
        'Tatsuro Nagamatsu (Gelandang Serang / Attacking Midfielder)',
        'Alwi Slamat (Gelandang Tengah / Central Midfielder)',
        'Pramoedya Putra (Gelandang Tengah / Central Midfielder)',
        'Adriano Duarte (Penyerang Sayap / Winger)',
        'Rifal Lastori (Penyerang Sayap / Winger)',
        'Frets Butuan (Penyerang Sayap / Winger)',
        'Yandi Sofyan (Penyerang Tengah / Center Forward)',
        'Victor Mansaray (Penyerang Tengah / Center Forward)',
        'Diego "China" Martinez (Penyerang Tengah / Center Forward)',
        'Ilham Udin Armaiyn (Penyerang Sayap / Winger)',
      ],
    },
    {
      id: 'persis',
      nama: 'Persis Solo',
      kota: 'Surakarta',
      logo: 'https://upload.wikimedia.org/wikipedia/id/thumb/d/d6/Persis_Solo_logo.svg/960px-Persis_Solo_logo.svg.png',
      tahunBerdiri: 1923,
      sejarah:
        'Salah satu dari tujuh klub pendiri PSSI. Memiliki sejarah panjang dalam perjuangan bangsa.',
      spesifikasi: {
        stadion: 'Manahan',
        kapasitas: '20,000',
        julukan: 'Laskar Sambernyawa',
        pelatih: 'Milomir Seslija',
      },
      prestasi: [
        { tahun: '2021', ket: 'Juara Liga 2 Indonesia.' },
        { tahun: '2023/24', ket: 'Peringkat 7 Liga 1.' },
      ],
      lineup: [
        'Muhammad Riyandi (Kiper / Goalkeeper)',
        'Gianluca Pandeynuwu (Kiper / Goalkeeper)',
        'Wahyu Tri Nugroho (Kiper / Goalkeeper)',
        'Ricardo Lima (Bek Tengah / Center Back)',
        'Jaimerson Xavier (Bek Tengah / Center Back)',
        'Fabiano Beltrame (Bek Tengah / Center Back)',
        'Rian Miziar (Bek Tengah / Center Back)',
        'Eduardo Kunde (Bek Tengah / Center Back)',
        'Gavin Kwan Adsit (Bek Kanan / Right Back)',
        'Eky Taufik (Bek Kanan / Right Back)',
        'Abduh Lestaluhu (Bek Kiri / Left Back)',
        'Giovani Numberi (Bek Kiri / Left Back)',
        'Sutanto Tan (Gelandang Bertahan / Defensive Midfielder)',
        'Alexis Messidoro (Gelandang Tengah / Central Midfielder)',
        'Sho Yamamoto (Gelandang Serang / Attacking Midfielder)',
        'Facundo Aranda (Gelandang Serang / Attacking Midfielder)',
        'Roni Gonzalez (Penyerang Sayap / Winger)',
        'Moussa Sidibe (Penyerang Sayap / Winger)',
        'Irfan Jauhari (Penyerang Sayap / Winger)',
        'Althaf Indie (Penyerang Sayap / Winger)',
        'Ramadhan Sananta (Penyerang Tengah / Center Forward)',
        'Fernando Rodriguez (Penyerang Tengah / Center Forward)',
        'Karim Rossi (Penyerang Tengah / Center Forward)',
        'Beto Goncalves (Penyerang Tengah / Center Forward)',
        'Ferdinand Sinaga (Penyerang Tengah / Center Forward)',
      ],
    },
    {
      id: 'psis',
      nama: 'PSIS Semarang',
      kota: 'Semarang',
      logo: 'https://upload.wikimedia.org/wikipedia/id/thumb/f/f5/PSIS_logo.svg/500px-PSIS_logo.svg.png',
      tahunBerdiri: 1932,
      sejarah:
        'Klub besar dari Jawa Tengah yang pernah menjuarai Liga Indonesia di era 1999.',
      spesifikasi: {
        stadion: 'Stadion Jatidiri',
        kapasitas: '25,000',
        julukan: 'Laskar Mahesa Jenar',
        pelatih: 'Gilbert Agius',
      },
      prestasi: [
        { tahun: '2023/24', ket: 'Peringkat 6 Liga 1.' },
        { tahun: '2024/25', ket: 'Fokus orbitkan pemain muda dari akademi.' },
      ],
      lineup: [
        'Adi Satryo (Kiper / Goalkeeper)',
        'Jandia Eka Putra (Kiper / Goalkeeper)',
        'Syahrul Trisna (Kiper / Goalkeeper)',
        'Wahyu Prasetyo (Bek Tengah / Center Back)',
        'Joao Ferrari (Bek Tengah / Center Back)',
        'Alfeandra Dewangga (Bek Tengah / Central Midfielder)',
        'Lucao (Bek Tengah / Center Back)',
        'Wallace Costa (Bek Tengah / Center Back)',
        'Fredyan Wahyu (Bek Kanan / Right Back)',
        'Haykal Alhafiz (Bek Kiri / Left Back)',
        'Frendi Saputra (Bek Kiri / Left Back)',
        'Boubakary Diarra (Gelandang Bertahan / Defensive Midfielder)',
        'Jonathan Cantillana (Gelandang Tengah / Central Midfielder)',
        'Luthfi Kamal (Gelandang Bertahan / Defensive Midfielder)',
        'Tri Setiawan (Gelandang Tengah / Central Midfielder)',
        'Septian David Maulana (Gelandang Serang / Attacking Midfielder)',
        'Taisei Marukawa (Penyerang Sayap / Winger)',
        'Gali Freitas (Penyerang Sayap / Winger)',
        'Vitinho (Penyerang Sayap / Winger)',
        'Riyan Ardiansyah (Penyerang Sayap / Winger)',
        'Carlos Fortes (Penyerang Tengah / Center Forward)',
        'Evandro Brandao (Penyerang Tengah / Center Forward)',
        'Bruno Silva (Penyerang Tengah / Center Forward)',
        'Hari Nur Yulianto (Penyerang Tengah / Center Forward)',
      ],
    },
    {
      id: 'madura-united',
      nama: 'Madura United FC',
      kota: 'Pamekasan',
      logo: 'https://upload.wikimedia.org/wikipedia/id/8/8a/Madura_United_FC.png',
      tahunBerdiri: 2016,
      sejarah:
        'Berasal dari akuisisi PBR, kini menjadi tim yang sangat disegani di Jawa Timur.',
      spesifikasi: {
        stadion: 'Gelora Bangkalan',
        kapasitas: '15,000',
        julukan: 'Laskar Sape Kerrab',
        pelatih: 'Widodo C. Putro',
      },
      prestasi: [
        { tahun: '2023/24', ket: 'Runner-up Liga 1 (Championship Series).' },
        {
          tahun: '2024/25',
          ket: 'Mewakili Indonesia di AFC Challenge League.',
        },
      ],
      lineup: [
        'Dida (Kiper / Goalkeeper)',
        'Lucas Frigeri (Kiper / Goalkeeper)',
        'Satria Tama (Kiper / Goalkeeper)',
        'Muhammad Ridho (Kiper / Goalkeeper)',
        'Christian Rontini (Bek Tengah / Center Back)',
        'Cleberson (Bek Tengah / Center Back)',
        'Fachruddin Aryanto (Bek Tengah / Center Back)',
        'Jaimerson Xavier (Bek Tengah / Center Back)',
        'Pedro Monteiro (Bek Tengah / Center Back)',
        'Koko Ari Araya (Bek Kanan / Right Back)',
        'Novan Setya Sasongko (Bek Kiri / Left Back)',
        'Reva Adi Utama (Bek Kiri / Left Back)',
        'Jordy Wehrmann (Gelandang Tengah / Central Midfielder)',
        'Jacob Mahler (Gelandang Bertahan / Defensive Midfielder)',
        'Jaja / Hugo Gomes (Gelandang Serang / Attacking Midfielder)',
        'Francisco Rivera (Gelandang Serang / Attacking Midfielder)',
        'Zulfiandi (Gelandang Bertahan / Defensive Midfielder)',
        'Rickii Ariansyah (Gelandang Tengah / Central Midfielder)',
        'Lulinha (Penyerang Sayap / Winger)',
        'Malik Risaldi (Penyerang Sayap / Winger)',
        'Bayu Gatra (Penyerang Sayap / Winger)',
        'Maxuel Silva (Penyerang Tengah / Center Forward)',
        'Dalberto (Penyerang Tengah / Center Forward)',
        'Beto Goncalves (Penyerang Tengah / Center Forward)',
        'Junior Brandao (Penyerang Tengah / Center Forward)',
      ],
    },
  ];

  constructor() {}

  // Fungsi untuk mengambil semua data tim (untuk halaman Home)
  getAllTeams() {
    return this.daftarTim;
  }

  // Fungsi untuk mengambil satu tim berdasarkan ID (untuk halaman Detail)
  getTeamById(id: string) {
    return this.daftarTim.find((team) => team.id === id);
  }
}
